### ISSUE TITLE
ripe on node 4

### ISSUE THREAD

**Issue by fheidrich** [Apercu/ripe#1]
I'm unable to install ripe latest (0.2.0) with the latest node (v4.1.1).
I suspect you just need to bump the ws version in package.json from 0.7.1 to 0.8.0

make: **\* [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/fheidric/npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/Users/fheidric/npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/node_modules/ripe/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
ripe@0.2.0 node_modules/ripe

**Comment by balthazar** [comment]
Published as 0.2.1, thanks for the heads-up! :)

**Comment by fheidrich** [comment]
Thank you! it worked for me.
